force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <description>Represents a food item that is available to be put into a food stand.</description>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Brief description of the food item.</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Food__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Cost of this food item.</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/foodRecordSearch.cls
public with sharing class foodRecordSearch {
    
    @AuraEnabled(cacheable=true)
    public static List<Food__c> retrieveRecords() {
        try {
            List<sObject> foodList = new List<Food__c>();
            foodList = [SELECT Id, Name, Price__c, Description__c FROM Food__c];

            return foodList;
        } catch (Exception ex) {
            System.debug(ex);
            return null;
        }
    }
}