force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <description>Represents a food item that is available to be put into a food stand.</description>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Stand__c/Food_Stand__c.object-meta.xml
<CustomObject>
    <description>Represents a real-world food stand in a customer&apos;s cafeteria, which holds a selection of products that the customer&apos;s employees or guests can buy.</description>
    <label>Food Stand</label>
    <nameField>
        <displayFormat>Stand{00000}</displayFormat>
        <label>Food Stand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Stands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Stand__c/fields/Item_List__c.field-meta.xml
<CustomField>
    <fullName>Item_List__c</fullName>
    <description>A listing of the items that are sold from this stand.</description>
    <inlineHelpText>A listing of the items that are sold from this stand.</inlineHelpText>
    <label>Item List</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Food_Stand__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of stand. Determines what food/beverages can be sold.</description>
    <inlineHelpText>The type of stand. Determines what food/beverages can be sold.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Rack</fullName>
                <default>true</default>
                <label>Open Rack</label>
            </value>
            <value>
                <fullName>Platter Tower</fullName>
            </value>
            <value>
                <fullName>Refrigerated Drink Rack</fullName>
            </value>
            <value>
                <fullName>Refrigerated Rack</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Cold Drink Dispenser</fullName>
            </value>
            <value>
                <fullName>Hot Drink Dispenser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

food-stand-selection/main/default/classes/foodStandUpdates.cls
/* A static class dedicated to supporting the foodStandSelector LWC.
 * Can provide the data needed to display the selector, and can take
 * updates to that data.
 */
public with sharing class foodStandUpdates {

    @AuraEnabled(cacheable=true)
    public static List<String> retrieveFoodNames() {
        List<String> results = new List<String>();
        List<Food__c> foods = [SELECT Name FROM Food__c];
        for(Food__c food : foods){
            results.add(food.Name);
        }
        return results;
    }

    // Used to get the data from the Food Stand so that the selector can be displayed.
    @AuraEnabled(cacheable=true)
    public static List<String> retrieveFoodStand(String id) {
        // Since we need to return the type of stand, as well as its contents, and whether or not they can be updated, we need a List.
        List<String> results = new List<String>();
        // Make sure the user can see food stands.
        if (Schema.SObjectType.Food_Stand__c.isAccessible()){
            // This needs to be in a try/catch in case someone tries to look up an Id that doesn't exist
            try{
                Food_Stand__c stand = [SELECT Type__c, Item_List__c FROM Food_Stand__c WHERE Id = :id LIMIT 1];
                // If no exception occurred, fill in the results normally. Of note, field-level security is ignored on purpose.

                /* The first result is special, in that it tells the state of the results. 
                 *
                 * There are four possible options:
                 * 
                 * Editable - Found the Food Stand, and you can edit its contents.
                 * Not Editable - Found the Food Stand, but you can't edit its contents.
                 * Not Found - Tried to find the Food Stand, but there was no matching Id.
                 * Inaccessible - You don't have permission to look up Food Stands.
                 */
                if (Schema.SObjectType.Food_Stand__c.isUpdateable()){
                    results.add('Editable');
                } else {
                    results.add('Not Editable');
                }
                // The second and third results only come back if the Food Stand was found. They are the Type and Item List.
                results.add(stand.Type__c);
                results.add(stand.Item_List__c);
            } catch (QueryException e){
                results.add('Not Found');
            }
        } else {
            results.add('Inaccessible');
        }
        // Whatever the results were, return them here.
        return results;
    }

    // Used to change the Food Stand's type on the backend. Returns false if it didn't work for any reason.
    @AuraEnabled
    public static Boolean updateFoodStandType(String id, String type) {
        if (Schema.SObjectType.Food_Stand__c.isUpdateable()){
            String newType = null;
            for(Schema.PicklistEntry picklistEntry : Food_Stand__c.fields.Type__c.getDescribe().getPicklistValues()) {
                if (picklistEntry.getValue() == type){
                    newType = picklistEntry.getValue();
                }
            }
            if (newType == null) return false;
            try{

                Food_Stand__c stand = [SELECT Type__c FROM Food_Stand__c WHERE Id = :id LIMIT 1];
                stand.Type__c = newType;
                update stand;
                return true;
            } catch (QueryException e){
                return false;
            }
        } else return false;
    }

    // Used to change the Food Stand's item list on the backend. Returns false if it didn't work for any reason.
    @AuraEnabled
    public static Boolean updateFoodStandList(String id, String newList) {
        if (Schema.SObjectType.Food_Stand__c.isUpdateable()){
            try{
                Food_Stand__c stand = [SELECT Item_List__c FROM Food_Stand__c WHERE Id = :id LIMIT 1];
                stand.Item_List__c = newList;
                
                update stand;
                return true;
            } catch (QueryException e){
                return false;
            }
        } else return false;
    }
}