force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <description>Represents a food item that is available to be put into a food stand.</description>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food__c/fields/In_Stock__c.field-meta.xml
<CustomField>
    <fullName>In_Stock__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows whether the item is currently in stock.</description>
    <label>In Stock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Food__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Cost of this food item.</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Food__c/fields/Units_Per_Case__c.field-meta.xml
<CustomField>
    <fullName>Units_Per_Case__c</fullName>
    <description>How many units come per case.</description>
    <label>Units Per Case</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Food_Stand__c/Food_Stand__c.object-meta.xml
<CustomObject>
    <description>Represents a real-world food stand in a customer&apos;s cafeteria, which holds a selection of products that the customer&apos;s employees or guests can buy.</description>
    <label>Food Stand</label>
    <nameField>
        <displayFormat>Stand{00000}</displayFormat>
        <label>Food Stand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Stands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Stand__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>The order that a customer placed that resulted in this Food Stand being set up.</description>
    <inlineHelpText>The order that a customer placed that resulted in this Food Stand being set up.</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Food Stands</relationshipLabel>
    <relationshipName>Food_Stands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Food_Stand__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of stand. Determines what food/beverages can be sold.</description>
    <inlineHelpText>The type of stand. Determines what food/beverages can be sold.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Rack</fullName>
                <default>true</default>
                <label>Open Rack</label>
            </value>
            <value>
                <fullName>Platter Tower</fullName>
            </value>
            <value>
                <fullName>Refrigerated Drink Rack</fullName>
            </value>
            <value>
                <fullName>Refrigerated Rack</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Cold Drink Dispenser</fullName>
            </value>
            <value>
                <fullName>Hot Drink Dispenser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

food-stand-selection/main/default/classes/foodStandTestData.cls
@isTest
public class foodStandTestData {

    public static List<sObject> pregenFoodStands() {
        List<sObject> thingsToInsert = new List<sObject>();

        Food__c chipBag = new Food__c(Name='Potato Chips', Price__c=1, Units_Per_Case__c=10, In_Stock__c=true);
        thingsToInsert.add(chipBag);
        chipBag = new Food__c(Name='Barbecue Chips', Price__c=1, Units_Per_Case__c=10, In_Stock__c=true);
        thingsToInsert.add(chipBag);
        chipBag = new Food__c(Name='Cheese Chips', Price__c=1, Units_Per_Case__c=10, In_Stock__c=true);
        thingsToInsert.add(chipBag);

        Account acc = new Account(Name='TestAcc');
        thingsToInsert.add(acc);
        Order ord = new Order(AccountId=acc.Id);
        thingsToInsert.add(ord);
        Food_Stand__c fs = new Food_Stand__c(Order__c=ord.Id, Type__c='Open Rack');
        thingsToInsert.add(fs);

        insert thingsToInsert;
        return thingsToInsert;
    }
    
}