force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <description>Represents a food item that is available to be put into a food stand.</description>
    <label>Food</label>
    <nameField>
        <label>Food Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food__c/fields/In_Stock__c.field-meta.xml
<CustomField>
    <fullName>In_Stock__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Shows whether the item is currently in stock.</description>
    <label>In Stock</label>
    <type>Checkbox</type>
</CustomField>

foodObjectDisplay/main/default/classes/preventOutOfStockOrderHelper.cls
public class preventOutOfStockOrderHelper {
    public static void checkOutOfStock(List<Opportunity> sales) {
        // Queries for relevant fields in Opportunity Object.
        List<Opportunity>checkStock = [SELECT Id, Name, Email, (SELECT In_Stock__c FROM Food__c) FROM Opportunity];

        // Checks queried fields if lookup Food Object is out of stock.
        // Prevents Opportunity creation if Food object is currently out of stock.
        for ( Opportunity o : checkStock ) {
            if (!o.In_Stock__c) {
                o.addError('This Opportunity is currently out of stock');

            }
        }
    }
}