force-app/main/default/objects/Food_Stand__c/Food_Stand__c.object-meta.xml
<CustomObject>
    <description>Represents a real-world food stand in a customer&apos;s cafeteria, which holds a selection of products that the customer&apos;s employees or guests can buy.</description>
    <label>Food Stand</label>
    <nameField>
        <displayFormat>Stand{00000}</displayFormat>
        <label>Food Stand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Food Stands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Stand__c/fields/Item_List__c.field-meta.xml
<CustomField>
    <fullName>Item_List__c</fullName>
    <description>A listing of the items that are sold from this stand.</description>
    <inlineHelpText>A listing of the items that are sold from this stand.</inlineHelpText>
    <label>Item List</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Food_Stand__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of stand. Determines what food/beverages can be sold.</description>
    <inlineHelpText>The type of stand. Determines what food/beverages can be sold.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open Rack</fullName>
                <default>true</default>
                <label>Open Rack</label>
            </value>
            <value>
                <fullName>Platter Tower</fullName>
            </value>
            <value>
                <fullName>Refrigerated Drink Rack</fullName>
            </value>
            <value>
                <fullName>Refrigerated Rack</fullName>
            </value>
            <value>
                <fullName>Freezer</fullName>
            </value>
            <value>
                <fullName>Cold Drink Dispenser</fullName>
            </value>
            <value>
                <fullName>Hot Drink Dispenser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

food-stand-selection/main/default/classes/foodStandHelpers.cls
/* A static class that holds helper logic to support triggers for the Food Stand custom object.
 * Can help clear the item list of a Food Stand whenever its Type is altered.
 */
public with sharing class foodStandHelpers {

    /* Takes in the previous version of the Food Stand record (or null, if this is an insert)
     * and the new version, and performs any adjustments needed.
     * Right now, that means checking to see if the Type has been changed (or never existed)
     * and, if so, resetting the Item List to an empty String.
     */
    public static void beforeUpdate(Food_Stand__c oldFoodStand, Food_Stand__c newFoodStand){
        if (oldFoodStand == null || oldFoodStand.Type__c != newFoodStand.Type__c){
            newFoodStand.Item_List__c = '';
        }
    }

}